### ISSUE TITLE
Create a independent PDB sanitize step before entering the haddock3 pipeline

### ISSUE THREAD

**Issue by joaomcteixeira** [haddocking/haddock3#143]
After the discussions in #140 and #142. PR #144 implements what is here discussed. The `preprocessing` steps happen **before** the haddock3 pipeline when the original input date is copied to the `run_dir/data` folder. The aim is also to have a `CLI` that the user can run and correct the PDBs (or `dry-run`) before submittting.

**Done:**

*The list follows the execution order defined in the [`process_pdbs`](https://github.com/haddocking/haddock3/blob/9afb64ecca2c89749e82eb375d826e842fa569e3/src/haddock/gear/preprocessing.py#L158) function, order matters:*

- [x] `ANISOU` records can be discarded (use `pdb_keepcoord`)
- [x] `REMARK lines are discarded` (use `pdb_keepcoord`)
- [x] Select `altloc` with the highest occupancy (waiting for https://github.com/haddocking/pdb-tools/pull/117 to be merged)
- [x] sets all `occupancy` to `1.00` (uses `pdb_occ`)
- [x] Rename the `MSE` residues (selenomethionine) to `MET`. Also if `MSE` are defined as `HETATM`, make them `ATOM`.
- [x] Rename `HSD`, `HSE`, `HIE`, `HID` to `HIS` and convert them also to `ATOM` if needed.
- [x] Corrects charge in ions
- [x] Supports all residues defined in `cns/toppar/*.top` files. Automatically retrieves new residues from those files.
- [x] Convert `ATOM` to `HETATM` for residues that are expected to be `HETATM`. If the user provides `.top` file also residues defined there get converted to `HETATM` if needed.
- [x] Convert `HETATM` to `ATOM` for residues that should be `ATOM` and are defined as `HETATM` (these are natural and modified aminoacids)
- [x] Remove unsupported `HETATM`. Accepts user `.top` file.
- [x] Remove unsupported `ATOM`.
- [x] Insertions (`AARG`, `BARG`) (uses `pdb_fixinsert`)
- [x] Renumbers atoms (uses `pdb_reatom` starting at 1)
- [ ] Renumbers residues (uses `pdb_reres` starting at 1) 
- [x] `pdb_tidy` (waiting https://github.com/haddocking/pdb-tools/pull/119)
- [x] address #138 
- [x] If input PDBs have the same chain ID (in different files) these are corrected such that all PDBs have different chains.

**Todo**
- [ ] Residues in the same chain cannot have repeated numbering
- [ ] If there is a gap in the sequence, the gap must be maintained (from the above list nothing corrects for this, so it should be as is, to be tested)
- [x] All models in an ensemble (`MODEL`) should be equal, that is, same labels.
- [x] Add flag to skip the `preprocessing` step

Probably good to check what our current 2.4 server machinery is doing in terms of input PDB validation

**Comment by rvhonorato** [comment]
I've added more points, the server also has checks specific to the `moleculetypes`

**Comment by joaomcteixeira** [comment]
When a PDB has multiple chains, what should be the behaviour? Keep only one chain or homogenize all chains to the same identifier?

**Comment by amjjbonvin** [comment]
Ideally we should offer different options to the user (I guess part of some config file):

1) Select a specific chain and sanitize

2) Keep all chains, shift the numbering to avoid overlap in residue numbering and assign a unique chainID

**Comment by joaomcteixeira** [comment]
Are ligands always given in independent PDBs, or can they be given in the same PDB together with the protein? And if the latter is the case, should `HETATM` be all at the end of the file, with `TER`, same chain?

**Comment by rvhonorato** [comment]
They can be either separated or together with any moleculetype actually, before or after the `ATOM`. Not sure about the effect of the `TER` record.

**Comment by joaomcteixeira** [comment]
`pdb_tidy` will add `TER` if there is an `ATOM`/`HETATM` break. If that can't be the case, I need to add something to tidy.

**Comment by rvhonorato** [comment]
Related? https://github.com/haddocking/pdb-tools/issues/101

**Comment by amjjbonvin** [comment]
Sounds fine to me.

And again, the ligand might be part of a PDB of a separate PDB on its own, depends on the docking scenario

> pdb_tidy will add TER if there is an ATOM/HETATM break. If that can't be the case, I need to add something to tidy.
>
